# Generated by Django 2.0.6 on 2018-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='post_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
