# Generated by Django 2.0.6 on 2018-07-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_picture_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
